# Generated by Django 5.0.7 on 2024-07-14 22:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('seguridad', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='role',
            field=models.CharField(choices=[('upper_level', 'Upper_Level'), ('medium_level', 'Medium_Level'), ('low_level', 'Low_Level')], default='low_level', max_length=100),
        ),
    ]
